server:
  port: 11086


spring:
  datasource:
    url: jdbc:mysql://43.131.33.18:9031/pokemoney?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    user:
      name: root
      password: 111