server:
  port: 8084

spring:
  datasource:
    url: jdbc:phoenix:43.131.33.18:2181
    driver-class-name: org.apache.phoenix.jdbc.PhoenixDriver

graphql:
  altair:
    enabled: true
    mapping: /api/v1/hadoop/client-api/altair
    subscriptions:
      timeout: 30
      reconnect: false
    static:
      base-path: /
    page-title: Altair
    cdn:
      enabled: false
      version: 4.0.2
    options:
      endpoint-url: /api/v1/hadoop/client-api/graphql
      subscriptions-endpoint: /subscriptions
      initial-settings:
        theme: dracula
#      initial-headers:
#        Authorization: "Bearer <your-token>"