server:
    port: 8081

dubbo:
    registry:
        address: nacos://localhost:8848
        group: dubbo-java-basic
        parameters:
            register-consumer-url: true
        subscribe: true
    protocol:
        name: tri
        port: 20910
    application:
        name: user-service
        qos-port: 22221
    config-center:
        address: nacos://localhost:8848
        group: dubbo-java-user-service
    metadata-report:
        address: nacos://localhost:8848
        group: dubbo-java-user-service
    provider:
        load-balance: p2c
    consumer:
        check: false

spring:
    jpa:
        database-platform: org.hibernate.dialect.MySQL8Dialect
        generate-ddl: true
        hibernate:
            ddl-auto: validate
    sharding-sphere:
        datasource:
            names: master0,master1,slave0,slave1
            master0:
                type: com.zaxxer.hikari.HikariDataSource
                driver-class-name: com.mysql.cj.jdbc.Driver
                jdbc-url: jdbc:mysql://43.131.33.18:4406/mydb?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
                username: root
                password: 111
            master1:
                type: com.zaxxer.hikari.HikariDataSource
                driver-class-name: com.mysql.cj.jdbc.Driver
                jdbc-url: jdbc:mysql://43.131.33.18:4406/my_db2?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
                username: root
                password: 111
            slave0:
                type: com.zaxxer.hikari.HikariDataSource
                driver-class-name: com.mysql.cj.jdbc.Driver
                jdbc-url: jdbc:mysql://43.131.33.18:5506/mydb?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
                username: root
                password: 111
            slave1:
                type: com.zaxxer.hikari.HikariDataSource
                driver-class-name: com.mysql.cj.jdbc.Driver
                jdbc-url: jdbc:mysql://43.131.33.18:5506/my_db2?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
                username: root
                password: 111

        props:
            sql-show: true
        rules:
            readwrite-splitting:
                data-sources:
                    readwrite_ds0:
                        load-balancer-name: round-robin
                        static-strategy:
                            write-data-source-name: master0
                            read-data-source-names: slave0
                    readwrite_ds1:
                        load-balancer-name: round-robin
                        static-strategy:
                            write-data-source-name: master1
                            read-data-source-names: slave1
                load-balancers:
                    round-robin:
                        type: ROUND_ROBIN
            sharding:
                default-database-strategy:
                    standard:
                        sharding-algorithm-name: database-inline
                        sharding-column: id
                default-table-strategy:
                    standard:
                        sharding-algorithm-name: table-inline
                        sharding-column: id
                sharding-algorithms:
                    table-inline:
                        type: INLINE
                        props:
                            algorithm-expression: t_users
                    database-inline:
                        type: INLINE
                        props:
                            algorithm-expression: readwrite_ds$->{id % 2}
                tables:
                    t_users:
                        actual-data-nodes: readwrite_ds0.t_users,readwrite_ds1.t_users
                        database-strategy:
                            standard:
                                sharding-algorithm-name: database-inline
                                sharding-column: id
                broadcast-tables:
                    - t_permissions
                    - t_roles


    #    datasource:
#        url: jdbc:mysql://127.0.0.1:3306/db_user?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        username: root
##        password:
## H2
##        url: jdbc:h2:mem:test_db
##        driverClassName: org.h2.Driver
##        username: admin
##        password: admin
#    jpa:
#        database-platform: org.hibernate.dialect.MySQL8Dialect
#        generate-ddl: true
#        hibernate.ddl-auto: update
#        open-in-view: false
#    h2.console.enabled: true
    mail:
        host: smtp.gmail.com
        port: 587
        username: chnduguyifei
        password: annysvynnlqnatrf
        properties:
            mail.smtp:
                auth: true
                starttls:
                    enable: true
                    required: true
