server:
    port: 8081

dubbo:
    registry:
        address: nacos://localhost:8848
        group: dubbo-java-basic
        parameters:
            register-consumer-url: true
        subscribe: true
    protocol:
        name: tri
        port: 20910
    application:
        name: user-service
        qos-port: 22221
    config-center:
        address: nacos://localhost:8848
        group: dubbo-java-user-service
    metadata-report:
        address: nacos://localhost:8848
        group: dubbo-java-user-service
    provider:
        load-balance: p2c
    consumer:
        check: false

spring:
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/db_user?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
#        password:
# H2
#        url: jdbc:h2:mem:test_db
#        driverClassName: org.h2.Driver
#        username: admin
#        password: admin
    jpa:
        database-platform: org.hibernate.dialect.MySQL8Dialect
        generate-ddl: true
        hibernate.ddl-auto: update
#        open-in-view: false
#    h2.console.enabled: true
    mail:
        host: smtp.gmail.com
        port: 587
        username: chnduguyifei
        password: annysvynnlqnatrf
        properties:
            mail.smtp:
                auth: true
                starttls:
                    enable: true
                    required: true
