server:
  port: 8082

dubbo:
  registry:
    address: nacos://localhost:8848
    group: dubbo-java
  protocol:
    name: tri
    port: 20890
  application:
    name: leaf-service-provider
    qos-port: 22222
  config-center:
    address: nacos://localhost:8848
    group: dubbo-java
  metadata-report:
    address: nacos://localhost:8848
    group: dubbo-java
  provider:
    load-balance: p2c
