server:
  port: 8083

dubbo:
  registry:
    address: nacos://localhost:8848
    group: dubbo-java
  protocol:
    name: tri
    port: 20880
  application:
    name: redis-service-provider
    qos-port: 22223
  config-center:
    address: nacos://localhost:8848
    group: dubbo-java
  metadata-report:
    address: nacos://localhost:8848
    group: dubbo-java
  provider:
    load-balance: p2c

spring.data.redis:
  host: localhost
  port: 6379
  lettuce.pool.max-active: 8
  lettuce.pool.max-wait: -1ms
  lettuce.pool.max-idle: 8
  lettuce.pool.min-idle: 0